---
name: Code Review

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

  actions: write
jobs:
  review:
    if: github.event.pull_request.draft == false
    uses: miikkak/workflows/.github/workflows/code-review.yml@ac2355b50ab91654be109a2a806004d3e2bd6f68 # main
    with:
      enabled: true
    secrets: inherit
