---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@ac2355b50ab91654be109a2a806004d3e2bd6f68 # main
    secrets: inherit
